ktor:
    application:
        modules:
            - app.mejourney.ApplicationKt.module
    deployment:
        port: 8080

mejourney:
  db:
    path: "/databases/mejourney.db"
  images:
    path: "/images"
